title: Ciencia con Python
author: Tangrama
description: Aprende simulación científica con Python

execute:
  execute_notebooks: "off"

html:
  home_page_in_navbar: true
  use_issues_button: false
  use_repository_button: false
  extra_css:
    - assets/css/custom.css
  extra_js:
    - assets/js/main.js

parse:
  myst_enable_extensions:
    - colon_fence
    - html_image

sphinx:
  extra_extensions:
    - sphinx_design
  config:
    html_show_sourcelink: false
    language: es
